// The campaign: 30 levels across 3 regions.
import type { LevelDef } from './levels';

const B = (t: number, n: number, step: number) => Array.from({ length: n }, (_, i) => t + i * step);

export const LEVELS: LevelDef[] = [
  // ------------------------------------------------------------------ GREEN VALLEY (bear)
  {
    id: 1, region: 'meadow', money: 200, animals: ['chicken'], slots: {},
    start: { animals: { chicken: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'egg', n: 6 }],
    gold: 60, silver: 100, tutorial: true,
    intro: 'Welcome to your new farm! Chickens eat grass and lay eggs. Collect 6 eggs.',
  },
  {
    id: 2, region: 'meadow', money: 350, animals: ['chicken'], slots: {},
    start: { animals: { chicken: 1 }, grass: 2 },
    goals: [{ kind: 'animals', animal: 'chicken', n: 5 }, { kind: 'collect', item: 'egg', n: 12 }],
    gold: 65, silver: 90,
    intro: 'Grow your flock! Sell eggs with the truck to earn money for more chickens.',
  },
  {
    id: 3, region: 'meadow', money: 350, animals: ['chicken'], slots: { T2: 'powder_plant' },
    start: { animals: { chicken: 2 }, grass: 2 },
    goals: [{ kind: 'collect', item: 'egg_powder', n: 5 }, { kind: 'money', n: 500 }],
    gold: 180, silver: 245,
    intro: 'Build an Egg Powder Plant on the empty lot. Click it to turn eggs into egg powder - it sells for much more!',
  },
  {
    id: 4, region: 'meadow', money: 400, animals: ['chicken'], slots: { T2: 'powder_plant' }, built: ['T2'],
    start: { animals: { chicken: 2 }, grass: 2 },
    goals: [{ kind: 'collect', item: 'egg_powder', n: 10 }, { kind: 'animals', animal: 'chicken', n: 7 }],
    gold: 100, silver: 140, predators: [60],
    intro: 'Watch out for bears! Click a bear several times to trap it in a cage, then click the cage to store it and sell it.',
  },
  {
    id: 5, region: 'meadow', money: 700, animals: ['chicken'], slots: { T1: 'powder_plant', T2: 'bakery' }, built: ['T1'], buy: ['flour'],
    start: { animals: { chicken: 3 }, grass: 2 },
    goals: [{ kind: 'collect', item: 'cookie', n: 5 }, { kind: 'collect', item: 'egg', n: 15 }],
    gold: 105, silver: 155, predators: [95],
    intro: 'The Bakery makes cookies from egg powder and flour. Buy flour in town with the helicopter!',
  },
  {
    id: 6, region: 'meadow', money: 1600, animals: ['chicken', 'sheep'], slots: { T1: 'powder_plant', T2: 'bakery', R1: 'spinnery' }, built: ['T1'], buy: ['flour'],
    start: { animals: { chicken: 3 }, grass: 2 },
    goals: [{ kind: 'collect', item: 'wool', n: 4 }, { kind: 'collect', item: 'yarn', n: 3 }, { kind: 'collect', item: 'cookie', n: 4 }],
    gold: 210, silver: 285, predators: [70, 170],
    intro: 'Sheep give wool! Spin wool into yarn at the Spinnery.',
  },
  {
    id: 7, region: 'meadow', money: 2200, animals: ['chicken', 'sheep'], pets: ['cat'],
    slots: { T1: 'powder_plant', T2: 'bakery', R1: 'spinnery', R2: 'loom' }, built: ['T1', 'R1'], buy: ['flour'],
    start: { animals: { chicken: 3, sheep: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'fabric', n: 4 }, { kind: 'collect', item: 'cookie', n: 6 }, { kind: 'animals', animal: 'sheep', n: 3 }],
    gold: 165, silver: 270, predators: [80, 180],
    intro: 'Weave yarn into fabric at the Loom. A cat can help: it collects products for you!',
  },
  {
    id: 8, region: 'meadow', money: 1800, animals: ['chicken', 'sheep'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', T3: 'cake_shop', R1: 'spinnery' }, built: ['T1', 'T2'], buy: ['flour'],
    start: { animals: { chicken: 4 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'cake', n: 3 }, { kind: 'collect', item: 'yarn', n: 6 }, { kind: 'money', n: 4000 }],
    gold: 330, silver: 445, predators: [60, 150, 230],
    intro: 'The Cake Shop bakes a cake from two cookies. A dog will chase bears away!',
  },
  {
    id: 9, region: 'meadow', money: 3000, animals: ['chicken', 'sheep'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', R1: 'spinnery', R2: 'loom', R3: 'tailor' }, built: ['T1', 'R1'], buy: ['flour', 'buttons'],
    start: { animals: { chicken: 4, sheep: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'shirt', n: 3 }, { kind: 'collect', item: 'cookie', n: 6 }, { kind: 'animals', animal: 'sheep', n: 4 }],
    gold: 325, silver: 440, predators: [80, 180, 260],
    intro: 'The Tailor sews shirts from fabric and buttons. Buttons come from town.',
  },
  {
    id: 10, region: 'meadow', money: 3500, animals: ['chicken', 'sheep'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', T3: 'cake_shop', R1: 'spinnery', R2: 'loom', R3: 'tailor' }, built: ['T1', 'R1'], buy: ['flour', 'buttons'],
    start: { animals: { chicken: 4, sheep: 2 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'cake', n: 5 }, { kind: 'collect', item: 'shirt', n: 4 }, { kind: 'money', n: 10000 }],
    gold: 440, silver: 595, predators: [70, 150, 230, 300],
    intro: 'The big harvest festival is coming! Show the valley what your farm can do.',
  },

  // ------------------------------------------------------------------ SUNNY SAVANNA (lion)
  {
    id: 11, region: 'savanna', money: 5500, animals: ['chicken', 'sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', R1: 'spinnery', R2: 'loom' }, built: ['T1', 'R1'],
    start: { animals: { chicken: 4, sheep: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'feather', n: 3 }, { kind: 'collect', item: 'fabric', n: 4 }, { kind: 'animals', animal: 'ostrich', n: 2 }],
    gold: 190, silver: 255, predators: [90],
    intro: 'Welcome to the savanna! Ostriches drop valuable feathers. Beware of lions!',
  },
  {
    id: 12, region: 'savanna', money: 6000, animals: ['sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', T3: 'pillow_factory' }, built: ['T1'],
    start: { animals: { sheep: 2 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'pillow', n: 3 }, { kind: 'collect', item: 'wool', n: 10 }],
    gold: 265, silver: 400, predators: [80, 200],
    intro: 'The Pillow Factory stuffs fabric with soft feathers. Pillows sell for a fortune!',
  },
  {
    id: 13, region: 'savanna', money: 5000, animals: ['chicken', 'sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', R1: 'spinnery', R2: 'loom', R3: 'pillow_factory' }, built: ['T1', 'R1'], buy: ['flour'],
    start: { animals: { chicken: 5, sheep: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'cookie', n: 8 }, { kind: 'collect', item: 'pillow', n: 4 }, { kind: 'money', n: 7500 }],
    gold: 515, silver: 765, predators: [70, 160, 250],
  },
  {
    id: 14, region: 'savanna', money: 9000, animals: ['sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { R1: 'spinnery', R2: 'loom', R3: 'tailor', T3: 'hat_shop' }, built: ['R1', 'R2'], buy: ['buttons'],
    start: { animals: { sheep: 2, ostrich: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'hat', n: 4 }, { kind: 'collect', item: 'shirt', n: 7 }],
    gold: 150, silver: 215, predators: [90, 200, 300],
    intro: 'The Hat Shop turns a shirt and a feather into a fancy hat. Very chic!',
  },
  {
    id: 15, region: 'savanna', money: 6500, animals: ['chicken', 'sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', T3: 'cake_shop', R1: 'spinnery', R2: 'loom', R3: 'tailor' }, built: ['T1', 'R1'], buy: ['flour', 'buttons'],
    start: { animals: { chicken: 5, sheep: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'cake', n: 4 }, { kind: 'collect', item: 'shirt', n: 3 }, { kind: 'animals', animal: 'ostrich', n: 3 }],
    gold: 425, silver: 620, predators: B(70, 4, 80),
  },
  {
    id: 16, region: 'savanna', money: 10000, animals: ['sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', T3: 'pillow_factory', R1: 'tailor', R2: 'hat_shop' }, built: ['T1', 'T2'], buy: ['buttons'],
    start: { animals: { sheep: 3, ostrich: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'pillow', n: 6 }, { kind: 'collect', item: 'hat', n: 2 }, { kind: 'money', n: 25000 }],
    gold: 370, silver: 660, predators: B(70, 4, 90),
  },
  {
    id: 17, region: 'savanna', money: 4000, animals: ['chicken', 'sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant' }, built: ['T1'],
    start: { animals: { chicken: 3 }, grass: 4 },
    goals: [{ kind: 'animals', animal: 'chicken', n: 10 }, { kind: 'animals', animal: 'sheep', n: 6 }, { kind: 'animals', animal: 'ostrich', n: 3 }, { kind: 'collect', item: 'egg', n: 40 }],
    gold: 400, silver: 540, predators: B(60, 5, 60),
    intro: 'A big zoo wants to see a thriving farm. Grow a huge herd - and keep the lions away!',
  },
  {
    id: 18, region: 'savanna', money: 8000, animals: ['chicken', 'sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', T3: 'cake_shop', R1: 'spinnery', R2: 'loom', R3: 'pillow_factory' }, built: ['T1', 'T2', 'R1'], buy: ['flour'],
    start: { animals: { chicken: 5, sheep: 2 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'cookie', n: 10 }, { kind: 'collect', item: 'cake', n: 4 }, { kind: 'collect', item: 'pillow', n: 4 }],
    gold: 360, silver: 520, predators: B(80, 4, 90),
  },
  {
    id: 19, region: 'savanna', money: 12000, animals: ['sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', T3: 'tailor', R1: 'pillow_factory', R2: 'hat_shop' }, built: ['T1', 'T2'], buy: ['buttons'],
    start: { animals: { sheep: 3, ostrich: 2 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'hat', n: 4 }, { kind: 'collect', item: 'pillow', n: 4 }, { kind: 'money', n: 35000 }],
    gold: 390, silver: 635, predators: B(70, 5, 80),
  },
  {
    id: 20, region: 'savanna', money: 12000, animals: ['chicken', 'sheep', 'ostrich'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', T3: 'tailor', R1: 'pillow_factory', R2: 'hat_shop', R3: 'powder_plant' }, built: ['T1', 'T2', 'R3'], buy: ['buttons'],
    start: { animals: { chicken: 4, sheep: 3, ostrich: 1 }, grass: 4 },
    goals: [{ kind: 'collect', item: 'hat', n: 4 }, { kind: 'collect', item: 'pillow', n: 5 }, { kind: 'money', n: 40000 }],
    gold: 500, silver: 860, predators: B(60, 6, 75),
    intro: 'The Savanna Grand Bazaar! Only the finest hats and pillows will do.',
  },

  // ------------------------------------------------------------------ FROSTY PEAKS (polar bear)
  {
    id: 21, region: 'arctic', money: 12000, animals: ['chicken', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'creamery' }, built: ['T1'],
    start: { animals: { chicken: 4, cow: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'milk', n: 10 }, { kind: 'collect', item: 'cream', n: 8 }, { kind: 'animals', animal: 'cow', n: 3 }],
    gold: 140, silver: 190, predators: [100],
    intro: 'Brrr! Cows give milk even in the snow. The Creamery turns milk into rich cream. Polar bears roam here!',
  },
  {
    id: 22, region: 'arctic', money: 14000, animals: ['cow'], pets: ['cat', 'dog'],
    slots: { T1: 'creamery', T2: 'cheese_factory' }, built: ['T1'],
    start: { animals: { cow: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'cheese', n: 8 }, { kind: 'collect', item: 'milk', n: 20 }],
    gold: 215, silver: 290, predators: [90, 210],
    intro: 'Age cream into delicious cheese at the Cheese Factory.',
  },
  {
    id: 23, region: 'arctic', money: 14000, animals: ['chicken', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', T3: 'creamery', R1: 'ice_cream_factory' }, built: ['T1', 'T3'], buy: ['flour'],
    start: { animals: { chicken: 4, cow: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'ice_cream', n: 9 }, { kind: 'collect', item: 'cookie', n: 16 }],
    gold: 230, silver: 460, predators: [80, 190, 290],
    intro: 'Ice cream in the arctic? Of course! Mix cream with a cookie at the Ice Cream Factory.',
  },
  {
    id: 24, region: 'arctic', money: 15000, animals: ['sheep', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', R1: 'creamery', R2: 'cheese_factory' }, built: ['T1', 'R1'],
    start: { animals: { sheep: 2, cow: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'cheese', n: 8 }, { kind: 'collect', item: 'fabric', n: 12 }, { kind: 'animals', animal: 'cow', n: 3 }],
    gold: 210, silver: 285, predators: B(80, 4, 90),
  },
  {
    id: 25, region: 'arctic', money: 15000, animals: ['chicken', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', T3: 'cake_shop', R1: 'creamery', R2: 'cheese_factory', R3: 'ice_cream_factory' }, built: ['T1', 'R1'], buy: ['flour'],
    start: { animals: { chicken: 5, cow: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'ice_cream', n: 6 }, { kind: 'collect', item: 'cheese', n: 5 }, { kind: 'collect', item: 'cake', n: 4 }],
    gold: 290, silver: 485, predators: B(70, 5, 80),
  },
  {
    id: 26, region: 'arctic', money: 18000, animals: ['sheep', 'ostrich', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', T3: 'tailor', R1: 'hat_shop', R2: 'creamery', R3: 'cheese_factory' }, built: ['T1', 'R2'], buy: ['buttons'],
    start: { animals: { sheep: 2, cow: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'shirt', n: 8 }, { kind: 'collect', item: 'hat', n: 5 }, { kind: 'collect', item: 'cheese', n: 6 }],
    gold: 305, silver: 445, predators: B(80, 5, 80),
  },
  {
    id: 27, region: 'arctic', money: 18000, animals: ['sheep', 'ostrich', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', T3: 'pillow_factory', R1: 'creamery', R2: 'cheese_factory' }, built: ['T1', 'R1'],
    start: { animals: { sheep: 2, ostrich: 1, cow: 1 }, grass: 3 },
    goals: [{ kind: 'collect', item: 'pillow', n: 5 }, { kind: 'collect', item: 'cheese', n: 5 }, { kind: 'money', n: 45000 }],
    gold: 480, silver: 660, predators: B(70, 5, 80),
  },
  {
    id: 28, region: 'arctic', money: 20000, animals: ['chicken', 'sheep', 'ostrich', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', R1: 'spinnery', R2: 'loom', R3: 'creamery', T3: 'cheese_factory' }, built: ['T1', 'R1'], buy: ['flour'],
    start: { animals: { chicken: 4, sheep: 1, cow: 1 }, grass: 4 },
    goals: [{ kind: 'animals', animal: 'cow', n: 5 }, { kind: 'animals', animal: 'ostrich', n: 3 }, { kind: 'animals', animal: 'sheep', n: 5 }, { kind: 'money', n: 35000 }],
    gold: 430, silver: 830, predators: B(60, 6, 70),
    intro: 'The Winter Fair is looking for the biggest herd in the north!',
  },
  {
    id: 29, region: 'arctic', money: 20000, animals: ['sheep', 'ostrich', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'spinnery', T2: 'loom', T3: 'tailor', R1: 'hat_shop', R2: 'creamery', R3: 'cheese_factory' }, built: ['T1', 'T2', 'R2'], buy: ['buttons'],
    start: { animals: { sheep: 3, ostrich: 1, cow: 1 }, grass: 4 },
    goals: [{ kind: 'collect', item: 'hat', n: 4 }, { kind: 'collect', item: 'cheese', n: 6 }, { kind: 'money', n: 60000 }],
    gold: 540, silver: 940, predators: B(60, 6, 75),
  },
  {
    id: 30, region: 'arctic', money: 25000, animals: ['chicken', 'cow'], pets: ['cat', 'dog'],
    slots: { T1: 'powder_plant', T2: 'bakery', T3: 'cake_shop', R1: 'creamery', R2: 'cheese_factory', R3: 'ice_cream_factory' }, built: ['T1', 'T2', 'R1'], buy: ['flour'],
    start: { animals: { chicken: 6, cow: 2 }, grass: 4 },
    goals: [{ kind: 'collect', item: 'ice_cream', n: 11 }, { kind: 'collect', item: 'cake', n: 9 }, { kind: 'collect', item: 'cheese', n: 8 }, { kind: 'money', n: 120000 }],
    gold: 725, silver: 980, predators: B(60, 7, 70),
    intro: 'The Grand Finale! Become the most famous farmer in the world!',
  },
];
